### ISSUE TITLE
Option to select notebook destination

### ISSUE THREAD

**Issue by ijstokes** [Anaconda-Platform/nb_anacondacloud#18]
Right now all uploaded content goes to the user's own account space.  It would be nice to give the option of having an alternative destination, e.g. a project or organization.  The could then be stored in the notebook meta-data and used as the pre-populated value on subsequent uploads.

**Comment by bollwyvl** [comment]
If a user has rights on another organization, that is offered as well:
![orgs](https://cloud.githubusercontent.com/assets/45380/14682241/b56845c0-06f2-11e6-932f-ce4520b97a3e.png)

Since i guess it is possible (tokens, etc) for a user to upload to something we can't discover easily, I guess one could have a text box....

**Comment by damianavila** [comment]
Again, I think this is enough solved with the current implementation, a text box could be an option but that would be a new feature...  and probably living in another issues (or renaming this one if you want).
